// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgz-NTXiQXOjLVW_iLp_QcxMH3VlzZDpw',
    appId: '1:71759817852:web:bb922b48c3d5635a5e2df9',
    messagingSenderId: '71759817852',
    projectId: 'restall-tech',
    authDomain: 'restall-tech.firebaseapp.com',
    storageBucket: 'restall-tech.appspot.com',
    measurementId: 'G-S9FVEXR7J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVr_QLkFUoTLoVQ0a6MGctw4ppZtEiQIo',
    appId: '1:71759817852:android:93c7f111c746dfc45e2df9',
    messagingSenderId: '71759817852',
    projectId: 'restall-tech',
    storageBucket: 'restall-tech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdkqNdqLU0_CC15q0Hi0hzSoVmjSdldDU',
    appId: '1:71759817852:ios:68e437e6bb3b89505e2df9',
    messagingSenderId: '71759817852',
    projectId: 'restall-tech',
    storageBucket: 'restall-tech.appspot.com',
    iosBundleId: 'com.startupsrl.restalltech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdkqNdqLU0_CC15q0Hi0hzSoVmjSdldDU',
    appId: '1:71759817852:ios:68e437e6bb3b89505e2df9',
    messagingSenderId: '71759817852',
    projectId: 'restall-tech',
    storageBucket: 'restall-tech.appspot.com',
    iosBundleId: 'com.startupsrl.restalltech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgz-NTXiQXOjLVW_iLp_QcxMH3VlzZDpw',
    appId: '1:71759817852:web:e89ad751e7b49b955e2df9',
    messagingSenderId: '71759817852',
    projectId: 'restall-tech',
    authDomain: 'restall-tech.firebaseapp.com',
    storageBucket: 'restall-tech.appspot.com',
    measurementId: 'G-JXESRSLRJQ',
  );

}