export interface User {
    userType: string;       // Tipo di utente (stringa)
    email: string;          // Email dell'utente (stringa)
    codFiscale?: string;    // Codice fiscale (facoltativo, stringa)
    cognome: string;        // Cognome dell'utente (stringa)
    completed: boolean;     // Stato completamento del profilo (booleano)
    context: string;        // Contesto (stringa)
    customerID?: string;    // ID cliente (facoltativo, stringa)
    dataNascita?: string;   // Data di nascita (facoltativo, stringa)
    id: string;             // ID univoco dell'utente (stringa)
    nome: string;           // Nome dell'utente (stringa)
    numTel?: string;        // Numero di telefono (facoltativo, stringa)
    parentId?: string;      // ID del genitore (facoltativo, stringa)
    password: string;       // Password (stringa)
    propicKey?: string;     // Chiave per immagine profilo (facoltativo, stringa)
    propicLocation?: string;// Posizione immagine profilo (facoltativo, stringa)
    referralCode?: string;  // Codice referral (facoltativo, stringa)
    verified: boolean;      // Stato verifica (booleano)
    profitfromShop?: number;// Profitto dal negozio (facoltativo, numero)
    connectAccountId?: string;
  }