// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFgEXW2Es_wPymbkWMFZ8efOlbq0c2XtU',
    appId: '1:393127159107:web:c299d70a7b9d36a94cbbf6',
    messagingSenderId: '393127159107',
    projectId: 'restall-406515',
    authDomain: 'restall-406515.firebaseapp.com',
    storageBucket: 'restall-406515.appspot.com',
    measurementId: 'G-J3P3DMVQ48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADVbgO6128775tCkb42_vDOjdwLlHVMeM',
    appId: '1:393127159107:android:2ab59991a16294864cbbf6',
    messagingSenderId: '393127159107',
    projectId: 'restall-406515',
    storageBucket: 'restall-406515.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoAeENxpAgI7WXeElf0_jLBLCAvjmwZ0Y',
    appId: '1:393127159107:ios:7ef368491cbcd0d44cbbf6',
    messagingSenderId: '393127159107',
    projectId: 'restall-406515',
    storageBucket: 'restall-406515.appspot.com',
    iosBundleId: 'com.startupsrl.restall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoAeENxpAgI7WXeElf0_jLBLCAvjmwZ0Y',
    appId: '1:393127159107:ios:67563b97d08ca0ea4cbbf6',
    messagingSenderId: '393127159107',
    projectId: 'restall-406515',
    storageBucket: 'restall-406515.appspot.com',
    iosBundleId: 'com.example.restall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFgEXW2Es_wPymbkWMFZ8efOlbq0c2XtU',
    appId: '1:393127159107:web:185a1d2136812da44cbbf6',
    messagingSenderId: '393127159107',
    projectId: 'restall-406515',
    authDomain: 'restall-406515.firebaseapp.com',
    storageBucket: 'restall-406515.appspot.com',
    measurementId: 'G-Z01S1SPWW8',
  );
}
